import { useEffect } from "react";
import type { GetServerSideProps, NextPage } from "next";
import { update } from "wow-stocks";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

async function start() {
  console.log("11111111111111111111111111111111111111111111");
  const { get, watch } = await update({
    length: 90, // 更新 90 个交易日所有股票的行情
  });
  // 基于已更新的数据获取一次行情

  console.log("2222222222222222222222222222");
  const quotations = await get();
  console.log("quotations 9999999999999999999999", quotations);
  // 基于已更新的数据监听实时行情
  // const stop = watch((quotations) => {
  //   // 可以在这里实时选股啦
  // });
  return { quotations }; // 停止监听
}

export const getServerSideProps: GetServerSideProps = async function (context) {
  console.log("main page context: ", context);
  const stock = await start();
  return { stock };
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
